version: '3.8'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lt-home-be
    env_file:
      - .env.prod
    ports:
      - '5000:5000'
    depends_on:
      - mysql
    links:
      - mysql
    command: >
      sh -c "
      yarn migration:run &&
      yarn create-user:data &&
      yarn start"
    # Ensure that the application waits for MySQL to be ready
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h mysql -u $MYSQL_USER -p$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - '3308:3306'
    env_file:
      - .env.prod
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
